trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
- script: dotnet build Complete-ASP-NET-Core-3-API/CommandAPISolution/src/CommandAPI/CommandAPI.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'